"""
LUMEN - shared engine.   *** DO NOT EDIT THIS FILE ***

You never change engine.py.  It opens the window, runs the game loop, reads the
keyboard, draws the ocean and the darkness, and keeps track of your submarine's
systems.  Each week your job is to fill in the marked sections of main.py.

If your instructor posts a newer engine.py, replace this whole file with it and
make sure ENGINE_VERSION below matches what the assignment says.
"""

import os
import json
import math
import random

ENGINE_VERSION = "1.0"

# ---------------------------------------------------------------------------
# Headless mode.  check.py sets LUMEN_HEADLESS=1 so the autograder can import
# main.py and call your functions without a window ever opening.
# ---------------------------------------------------------------------------
os.environ.setdefault("PYGAME_HIDE_SUPPORT_PROMPT", "1")

HEADLESS = os.environ.get("LUMEN_HEADLESS") == "1"
if HEADLESS:
    os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
    os.environ.setdefault("SDL_AUDIODRIVER", "dummy")

import pygame  # noqa: E402  - must come after the env vars above

# ---------------------------------------------------------------------------
# Tunable constants
# ---------------------------------------------------------------------------
WIDTH, HEIGHT = 960, 600
FPS = 60
SUB_SCREEN_Y = int(HEIGHT * 0.42)      # the sub is pinned here; the world scrolls
PIXELS_PER_METER = 4.0

SURFACE_COLOR = (14, 32, 48)
DEEP_COLOR = (2, 4, 9)

DEFAULT_DIVEPLAN = {
    "pilot": "Unknown",
    "target_depth": 300,
    "ballast_kg": 40.0,
    "battery_pct": 100.0,
}

# ---------------------------------------------------------------------------
# Internal per-run state (the engine's scratch space - you never touch this)
# ---------------------------------------------------------------------------
class _State:
    def __init__(self):
        self.dt = 0.0
        self.t = 0.0
        self.frame = 0
        self.snow = []
        self.screen = None
        self.hud_surface = None    # dashboard layer, always drawn on top of the dark

_state = _State()


def dt():
    """Seconds elapsed since the previous frame (a small float like 0.016)."""
    return _state.dt


def now():
    """Seconds since the game started."""
    return _state.t


# ---------------------------------------------------------------------------
# Dive plan  -  written by your Module 2 code, read by the game
# ---------------------------------------------------------------------------
def save_diveplan(pilot, target_depth, ballast_kg, battery_pct, path="diveplan.json"):
    """Save the four dive-plan values to diveplan.json.  Values are stored
    exactly as you pass them in."""
    plan = {
        "pilot": pilot,
        "target_depth": target_depth,
        "ballast_kg": ballast_kg,
        "battery_pct": battery_pct,
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(plan, f, indent=2)
    return plan


def load_diveplan(path="diveplan.json"):
    """Return the dive-plan dict.  Falls back to defaults if the file is
    missing or corrupt (you write that handling properly in Module 6)."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (FileNotFoundError, ValueError, OSError):
        return dict(DEFAULT_DIVEPLAN)
    merged = dict(DEFAULT_DIVEPLAN)
    if isinstance(data, dict):
        merged.update(data)
    return merged


def _as_float(value, fallback):
    try:
        return float(value)
    except (TypeError, ValueError):
        return float(fallback)


# ---------------------------------------------------------------------------
# The submarine - a plain bag of values the engine keeps updated every frame.
# You read these (sub.depth, sub.oxygen, ...).  From Module 10 you rebuild it.
# ---------------------------------------------------------------------------
class Submarine:
    def __init__(self, plan):
        self.pilot = plan.get("pilot", "Unknown")
        self.depth = 0.0                                    # meters below surface
        self.x = 0.0                                        # horizontal drift
        self.target_depth = _as_float(plan.get("target_depth"), 300)
        self.oxygen = 100.0                                 # percent
        self.power = _as_float(plan.get("battery_pct"), 100.0)   # percent
        self.ballast = _as_float(plan.get("ballast_kg"), 40.0)   # kg
        self.hull = 100.0                                   # integrity percent
        self.rated_depth = 1000.0                           # crush past here
        # heavier ballast sinks faster: 40 kg -> the old default of 20 m/s
        self.dive_rate = 8.0 + self.ballast * 0.3          # meters / second
        self.rise_rate = 24.0
        self.light_on = True
        self.light_radius = 155
        self.alive = True
        # one-frame request flags - main.py sets these, the engine consumes them
        self.descending = False
        self.ascending = False


# ---------------------------------------------------------------------------
# Keyboard - a tiny wrapper so main.py never has to import pygame constants
# ---------------------------------------------------------------------------
_KEYMAP = {
    "UP": pygame.K_UP, "DOWN": pygame.K_DOWN, "LEFT": pygame.K_LEFT,
    "RIGHT": pygame.K_RIGHT, "SPACE": pygame.K_SPACE,
    "W": pygame.K_w, "A": pygame.K_a, "S": pygame.K_s, "D": pygame.K_d,
    "L": pygame.K_l, "E": pygame.K_e, "TAB": pygame.K_TAB,
}
_held = set()
_pressed = set()


def key_down(name):
    """True for as long as the named key is held down.
    Names: UP DOWN LEFT RIGHT SPACE W A S D L E TAB"""
    return _KEYMAP.get(name.upper()) in _held


def key_pressed(name):
    """True only on the single frame the key is first pressed."""
    return _KEYMAP.get(name.upper()) in _pressed


# ---------------------------------------------------------------------------
# Drawing helpers
# ---------------------------------------------------------------------------
_font_cache = {}


def _font(size):
    if size not in _font_cache:
        _font_cache[size] = pygame.font.SysFont("consolas,couriernew,monospace", size)
    return _font_cache[size]


def draw_text(surface, text, pos, size=18, color=(198, 216, 232), anchor="topleft"):
    """Draw a line of text.  anchor can be 'topleft', 'center', 'midtop', etc."""
    img = _font(size).render(str(text), True, color)
    rect = img.get_rect()
    setattr(rect, anchor, (int(pos[0]), int(pos[1])))
    surface.blit(img, rect)
    return rect


def draw_glow(surface, pos, radius, color):
    """A soft additive glow - the look of everything alive down here."""
    x, y = int(pos[0]), int(pos[1])
    radius = max(2, int(radius))
    layers = 6
    for i in range(layers, 0, -1):
        r = max(1, int(radius * i / layers))
        a = int(70 * (1 - i / (layers + 1)))
        blob = pygame.Surface((r * 2, r * 2), pygame.SRCALPHA)
        pygame.draw.circle(blob, (color[0], color[1], color[2], a), (r, r), r)
        surface.blit(blob, (x - r, y - r), special_flags=pygame.BLEND_ADD)


def _hud_surface():
    if _state.hud_surface is None:
        _state.hud_surface = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
    return _state.hud_surface


def draw_hud_text(text, pos, size=16, color=(198, 216, 232), anchor="topleft"):
    """Draw a line of dashboard text that stays visible no matter how dark or
    deep you are - like an instrument on the cockpit panel, not a light shining
    into the water. Use this instead of draw_text for status readouts inside
    frame(); use draw_text for anything that should be hidden by the dark."""
    draw_text(_hud_surface(), text, pos, size=size, color=color, anchor=anchor)


def world_y_to_screen(sub, world_depth):
    """Convert a depth in meters to a y pixel, given where the sub is now."""
    return int(SUB_SCREEN_Y + (world_depth - sub.depth) * PIXELS_PER_METER)


def depth_zone_name(depth):
    """Rough name for the water at this depth (you build the real version in Module 9)."""
    if depth < 200:
        return "SUNLIT"
    if depth < 1000:
        return "TWILIGHT"
    if depth < 4000:
        return "MIDNIGHT"
    return "ABYSSAL"


# --- the pieces the engine always draws itself -----------------------------
def _draw_background(screen, sub):
    top_depth = sub.depth - SUB_SCREEN_Y / PIXELS_PER_METER
    step = 6
    for band_y in range(0, HEIGHT, step):
        d = top_depth + band_y / PIXELS_PER_METER
        k = max(0.0, min(1.0, d / 1400.0))
        col = (
            int(SURFACE_COLOR[0] + (DEEP_COLOR[0] - SURFACE_COLOR[0]) * k),
            int(SURFACE_COLOR[1] + (DEEP_COLOR[1] - SURFACE_COLOR[1]) * k),
            int(SURFACE_COLOR[2] + (DEEP_COLOR[2] - SURFACE_COLOR[2]) * k),
        )
        pygame.draw.rect(screen, col, (0, band_y, WIDTH, step))
    # the surface itself, if it is on screen
    surf_y = world_y_to_screen(sub, 0.0)
    if -20 <= surf_y <= HEIGHT:
        pygame.draw.line(screen, (120, 170, 190), (0, surf_y), (WIDTH, surf_y), 2)


def _draw_snow(screen, sub):
    if not _state.snow:
        for _ in range(90):
            _state.snow.append([random.uniform(0, WIDTH), random.uniform(0, HEIGHT),
                                random.uniform(6, 18)])
    for p in _state.snow:
        p[1] += (12 + p[2]) * _state.dt
        if p[1] > HEIGHT:
            p[1] -= HEIGHT
            p[0] = random.uniform(0, WIDTH)
        shade = int(70 + p[2] * 6)
        screen.fill((shade, shade, shade + 10),
                    (int(p[0]), int(p[1]), 2, 2))


def _draw_submarine(screen, sub):
    x, y = WIDTH // 2 + int(sub.x), SUB_SCREEN_Y
    if sub.light_on and sub.power > 0:
        cone = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
        pygame.draw.polygon(cone, (80, 110, 90, 26),
                            [(x, y), (x - 220, y + 260), (x + 220, y + 260)])
        screen.blit(cone, (0, 0), special_flags=pygame.BLEND_ADD)
    pygame.draw.ellipse(screen, (168, 176, 184), (x - 26, y - 12, 52, 24))
    pygame.draw.circle(screen, (230, 245, 255), (x + 14, y), 5)
    pygame.draw.rect(screen, (120, 130, 138), (x - 34, y - 4, 10, 8))


def _draw_darkness(screen, sub):
    murk = int(max(0.0, min(1.0, sub.depth / 320.0)) * 236)
    if murk <= 0:
        return
    dark = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
    dark.fill((0, 0, 4, murk))
    if sub.light_on and sub.power > 0:
        r = sub.light_radius
        hole = pygame.Surface((r * 2, r * 2), pygame.SRCALPHA)
        rings = 14
        for i in range(rings, 0, -1):
            rr = int(r * i / rings)
            a = int(murk * (1 - i / rings))
            pygame.draw.circle(hole, (0, 0, 0, a), (r, r), rr)
        dark.blit(hole, (WIDTH // 2 + int(sub.x) - r, SUB_SCREEN_Y - r),
                  special_flags=pygame.BLEND_RGBA_SUB)
    screen.blit(dark, (0, 0))


def _bar(screen, label, value, x, y, good=(80, 200, 140), bad=(210, 90, 80)):
    value = max(0.0, min(100.0, value))
    k = value / 100.0
    col = (int(bad[0] + (good[0] - bad[0]) * k),
           int(bad[1] + (good[1] - bad[1]) * k),
           int(bad[2] + (good[2] - bad[2]) * k))
    draw_text(screen, label, (x, y), size=14, color=(150, 165, 178))
    pygame.draw.rect(screen, (28, 34, 42), (x + 46, y + 2, 120, 10))
    pygame.draw.rect(screen, col, (x + 46, y + 2, int(120 * k), 10))


def _draw_target_line(screen, sub):
    """A dashed line across the water at the pilot's target depth, once it's
    close enough to be on screen."""
    y = world_y_to_screen(sub, sub.target_depth)
    if not (-30 <= y <= HEIGHT + 30):
        return
    col = (90, 210, 150) if sub.depth >= sub.target_depth else (90, 175, 210)
    for x in range(16, WIDTH - 16, 18):
        pygame.draw.line(screen, col, (x, int(y)), (x + 9, int(y)), 2)
    draw_text(screen, "TARGET DEPTH", (WIDTH // 2, int(y) - 16), size=12,
              color=col, anchor="midtop")


def _draw_base_hud(screen, sub):
    _bar(screen, "O2", sub.oxygen, 16, 14)
    _bar(screen, "PWR", sub.power, 16, 32)
    _bar(screen, "HULL", sub.hull, 16, 50)
    draw_text(screen, f"DEPTH {sub.depth:6.1f} m", (16, 74), size=16, color=(180, 205, 220))
    draw_text(screen, depth_zone_name(sub.depth), (16, 94), size=13, color=(120, 140, 155))

    if sub.depth >= sub.target_depth:
        draw_text(screen, f"TARGET {int(sub.target_depth)} m  -  REACHED",
                  (16, 112), size=13, color=(90, 210, 150))
    else:
        draw_text(screen, f"TARGET {int(sub.target_depth)} m  "
                  f"({sub.target_depth - sub.depth:.0f} m to go)",
                  (16, 112), size=13, color=(120, 170, 190))
    draw_text(screen, f"BALLAST {sub.ballast:.0f} kg  ->  DIVE {sub.dive_rate:.0f} m/s",
              (16, 130), size=13, color=(120, 140, 155))
    draw_text(screen, f"PILOT  {str(sub.pilot).upper()}", (WIDTH - 16, 14),
              size=14, color=(150, 165, 178), anchor="topright")


def draw_tick(screen, y, depth_m):
    """Draw one depth marker on the cockpit gauge: a short line at the right
    edge and a meter label.  Always visible, like the rest of the dashboard, no
    matter how dark it gets outside.  Markers off the top or bottom of the
    window are skipped for you."""
    if -24 <= y <= HEIGHT + 24:
        surf = _hud_surface()
        pygame.draw.line(surf, (86, 116, 132), (WIDTH - 58, int(y)),
                         (WIDTH - 22, int(y)), 1)
        draw_text(surf, f"{depth_m} m", (WIDTH - 62, int(y) - 7), size=12,
                  color=(118, 148, 163), anchor="topright")


def draw_hull_status(screen, status):
    """Show your Module 3 hull check.  Pass the string 'OK', 'CAUTION' or
    'BREACH'.  Drawn on the dashboard, so it stays visible in total darkness -
    just like the O2 / PWR / HULL bars in the top-left."""
    colors = {"OK": (90, 200, 150), "CAUTION": (230, 190, 90), "BREACH": (230, 90, 80)}
    text = status if status in colors else f"?{status}?"
    draw_hud_text(f"HULL: {text}", (WIDTH // 2, 16), size=20,
                  color=colors.get(status, (230, 90, 80)), anchor="midtop")


def draw_banner(screen, line1, line2=""):
    """A centered two-line message (used for game over, checkpoints, etc.)."""
    veil = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
    veil.fill((0, 0, 6, 180))
    screen.blit(veil, (0, 0))
    draw_text(screen, line1, (WIDTH // 2, HEIGHT // 2 - 20), size=34,
              color=(220, 235, 245), anchor="center")
    if line2:
        draw_text(screen, line2, (WIDTH // 2, HEIGHT // 2 + 24), size=18,
                  color=(150, 170, 185), anchor="center")


# ---------------------------------------------------------------------------
# System simulation the engine runs for you (Module 5+ you take parts over)
# ---------------------------------------------------------------------------
def _update_systems(sub):
    d = _state.dt
    if not sub.alive:
        return
    if sub.descending:
        sub.depth += sub.dive_rate * d
    if sub.ascending:
        sub.depth = max(0.0, sub.depth - sub.rise_rate * d)
    sub.descending = False          # must be re-requested every frame
    sub.ascending = False

    sub.oxygen = max(0.0, sub.oxygen - (0.55 + sub.depth / 5000.0) * d)
    if sub.light_on and sub.power > 0:
        sub.power = max(0.0, sub.power - 0.45 * d)
    if sub.power <= 0:
        sub.light_on = False
    if sub.depth > sub.rated_depth:
        sub.hull = max(0.0, sub.hull - (sub.depth - sub.rated_depth) * 0.02 * d)
    if sub.oxygen <= 0 or sub.hull <= 0:
        sub.alive = False


# ---------------------------------------------------------------------------
# Entry points
# ---------------------------------------------------------------------------
def _pump_events():
    global _pressed
    _pressed = set()
    running = True
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            running = False
        elif e.type == pygame.KEYDOWN:
            if e.key == pygame.K_ESCAPE:
                running = False
            _held.add(e.key)
            _pressed.add(e.key)
        elif e.type == pygame.KEYUP:
            _held.discard(e.key)
    return running


def show_briefing(pilot, target_depth, ballast_kg, battery_pct):
    """Open a small window that displays the dive plan your Module 2 code built.
    Does nothing in headless mode.  Press ESC or close the window to continue."""
    if HEADLESS:
        return
    pygame.init()
    screen = pygame.display.set_mode((WIDTH, HEIGHT))
    pygame.display.set_caption(f"LUMEN - pre-dive briefing   [engine {ENGINE_VERSION}]")
    clock = pygame.time.Clock()
    lines = [
        ("PRE-DIVE BRIEFING", 30, (220, 235, 245)),
        (f"pilot            {pilot}", 20, (190, 210, 224)),
        (f"target depth     {target_depth} m", 20, (190, 210, 224)),
        (f"ballast          {ballast_kg} kg", 20, (190, 210, 224)),
        (f"battery          {battery_pct} %", 20, (190, 210, 224)),
        ("ESC / close window to launch", 14, (120, 140, 155)),
    ]
    running = True
    while running:
        clock.tick(FPS)
        _state.dt = 1 / FPS
        running = _pump_events()
        screen.fill((8, 18, 28))
        pygame.draw.line(screen, (70, 110, 130), (60, 150), (WIDTH - 60, 150), 1)
        y = 90
        for text, size, color in lines:
            draw_text(screen, text, (80, y), size=size, color=color)
            y += size + 22
        _draw_snow(screen, Submarine(DEFAULT_DIVEPLAN))
        pygame.display.flip()
    pygame.quit()


def run(frame_fn, setup_fn=None, title="LUMEN - a descent"):
    """Open the game window and run the loop.  Every frame the engine draws the
    ocean, then calls YOUR frame_fn(sub, screen), then draws the sub, the
    darkness and the base HUD.  Anything you draw with draw_hud_text (or via
    draw_hull_status / draw_tick) is composited back on TOP of the darkness, so
    dashboard readouts never get swallowed by the dark, only the world outside
    your window does.  ESC or the window's close button quits."""
    if HEADLESS:
        return
    plan = load_diveplan()
    pygame.init()
    screen = pygame.display.set_mode((WIDTH, HEIGHT))
    pygame.display.set_caption(f"{title}   [engine {ENGINE_VERSION}]")
    _state.screen = screen
    clock = pygame.time.Clock()
    sub = Submarine(plan)
    if setup_fn is not None:
        setup_fn(sub)

    running = True
    while running:
        _state.dt = clock.tick(FPS) / 1000.0
        _state.t += _state.dt
        _state.frame += 1
        running = _pump_events()

        _update_systems(sub)
        _hud_surface().fill((0, 0, 0, 0))      # clear last frame's dashboard text

        _draw_background(screen, sub)
        _draw_snow(screen, sub)
        frame_fn(sub, screen)
        _draw_submarine(screen, sub)
        _draw_darkness(screen, sub)
        _draw_target_line(screen, sub)
        screen.blit(_state.hud_surface, (0, 0))    # dashboard on top - always visible
        _draw_base_hud(screen, sub)
        if not sub.alive:
            reason = "OXYGEN DEPLETED" if sub.oxygen <= 0 else "HULL BREACH"
            draw_banner(screen, "LOST WITH ALL HANDS",
                        f"{str(sub.pilot).upper()}  -  {reason}")

        pygame.display.flip()

    pygame.quit()


# A no-argument fallback so `python engine.py` shows something rather than nothing.
if __name__ == "__main__":
    def _demo(sub, screen):
        if key_down("DOWN"):
            sub.descending = True
        if key_down("UP"):
            sub.ascending = True
        if key_pressed("L"):
            sub.light_on = not sub.light_on
        draw_hull_status(screen, "OK" if sub.depth < sub.rated_depth else "BREACH")
        draw_hud_text("engine self-test  -  DOWN/UP dive, L light, ESC quit",
                      (16, HEIGHT - 28), size=13, color=(120, 140, 155))
    run(_demo, title="LUMEN engine self-test")
